Repository DTUSoftware/Matador, pull requests merged in 2022-01, with the labels that each got.

#2 Danish language field names
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#3 Make the GameBoard work with the new field JSON
  src/main/java/dk/dtu/matador/managers/DeedManager.java
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/managers/LanguageManager.java
  src/main/java/dk/dtu/matador/objects/Deed.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/fields/BreweryField.java
  src/main/java/dk/dtu/matador/objects/fields/FerryField.java
  src/main/java/dk/dtu/matador/objects/fields/PropertyField.java
  src/main/java/dk/dtu/matador/objects/fields/StreetField.java
  src/main/java/dk/dtu/matador/objects/fields/TaxField.java
  src/main/resources/GameBoard.json
  src/main/resources/GameMessages_de.properties
  src/main/resources/GameMessages_en.properties
Labels: bug

#15 Jailupdate and move field patch
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/Player.java
  src/main/java/dk/dtu/matador/objects/fields/JailField.java
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#17 Language checkup fixes, and grammar
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/resources/GameMessages_da.properties
Labels: bug, enhancement

#16 Houses and hotels
  src/main/java/dk/dtu/matador/Game.java
  src/main/java/dk/dtu/matador/managers/DeedManager.java
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/Deed.java
  src/main/java/dk/dtu/matador/objects/fields/JailField.java
  src/main/java/dk/dtu/matador/objects/fields/StreetField.java
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#14 Test
  src/main/resources/DesignClassDiagram-chancecards.png
  src/main/resources/DesignClassDiagram-fields.png
  src/main/resources/DesignClassDiagram.png
  src/main/resources/DomainModel.png
  src/main/resources/GameMessages_da.properties
  src/main/resources/SystemSequenceDiagram.png
  src/main/resources/UseCaseDiagram.png
  src/test/java/dk/dtu/matador/TestChanceCards.java
  src/test/java/dk/dtu/matador/TestDeedManager.java
  src/test/java/dk/dtu/matador/TestField.java
  src/test/java/dk/dtu/matador/TestFields.java
  src/test/java/dk/dtu/matador/TestLanguageManager.java
  src/test/java/dk/dtu/matador/TestPlayerManager.java
Labels: enhancement

#21 Net-worth of players
  src/main/java/dk/dtu/matador/managers/DeedManager.java
  src/main/java/dk/dtu/matador/objects/Deed.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/Player.java
  src/main/resources/GameBoard.json
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#24 Changes to the board to match the real board IRL
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/fields/BreakField.java
  src/main/java/dk/dtu/matador/objects/fields/BreweryField.java
  src/main/java/dk/dtu/matador/objects/fields/ChanceField.java
  src/main/java/dk/dtu/matador/objects/fields/FerryField.java
  src/main/java/dk/dtu/matador/objects/fields/Field.java
  src/main/java/dk/dtu/matador/objects/fields/GoToJailField.java
  src/main/java/dk/dtu/matador/objects/fields/JailField.java
  src/main/java/dk/dtu/matador/objects/fields/PropertyField.java
  src/main/java/dk/dtu/matador/objects/fields/StartField.java
  src/main/java/dk/dtu/matador/objects/fields/StreetField.java
  src/main/java/dk/dtu/matador/objects/fields/TaxField.java
  src/main/resources/GameBoard.json
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#26 Street, brewery and ferry property subtype
  src/main/java/dk/dtu/matador/managers/DeedManager.java
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/Deed.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/fields/BreweryField.java
  src/main/java/dk/dtu/matador/objects/fields/FerryField.java
  src/main/java/dk/dtu/matador/objects/fields/Field.java
  src/main/java/dk/dtu/matador/objects/fields/PropertyField.java
  src/main/java/dk/dtu/matador/objects/fields/StreetField.java
Labels: enhancement

#29 Tax field
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/objects/Player.java
  src/main/java/dk/dtu/matador/objects/fields/TaxField.java
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#30 Trading with other players
  src/main/java/dk/dtu/matador/managers/GUIManager.java
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/fields/PropertyField.java
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#34 Chance cards
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/Player.java
  src/main/java/dk/dtu/matador/objects/chancecards/BailCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/BoardWalkCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/ChanceCard.java
  src/main/java/dk/dtu/matador/objects/chancecards/DidHomeWorkCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/EatCandyCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/LightBlueCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/LightblueYellowCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/MoveFieldsCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/MoveOrDrawCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/OrangeBlueCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/SalmonGreenCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/SkateparkCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/StartCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/misc/KingsBirthdayCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/misc/MiscCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToFredriksberg.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToGrønningen.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToJail.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToMolslinien.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToNearestFerry.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToNearestFerryDouble.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToRådhusplads.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToStart.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToStrandvejen.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/GoToVimmelskaftet.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/Move3Back.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/Move3Forward.java
  src/main/java/dk/dtu/matador/objects/chancecards/move/MoveToFieldCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/BuyBeer.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/CarEnsurance.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/CarRepair.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/Carwash.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/Dentist.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/IllegalCigs.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/IllegalStop.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/NewTyres.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/OilPrices.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/ParkingTicket.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/PayCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/pay/PropertyTax.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/Aktie.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/Birthday.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/EllevenRight.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/FamilyParty.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/Garden.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/JointParty.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/MatadorLegatet.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/OldFurniture.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/PremiumBond.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/Raise.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/ReceiveCC.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/TheClassLottery.java
  src/main/java/dk/dtu/matador/objects/chancecards/receive/TheLocalAuthority.java
  src/main/java/dk/dtu/matador/objects/fields/JailField.java
  src/main/resources/GameMessages_da.properties
Labels: enhancement

#36 Fix tests and patch trading on bankruptcy
  src/main/java/dk/dtu/matador/managers/GameManager.java
  src/main/java/dk/dtu/matador/objects/GameBoard.java
  src/main/java/dk/dtu/matador/objects/Player.java
  src/main/java/dk/dtu/matador/objects/fields/BreakField.java
  src/main/resources/GameMessages_da.properties
  src/main/resources/GameMessages_en.properties
Labels: bug
